Write a function so that the columns of the output matrix are powers of the input
vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np

def vander_mat(x,N,increasing):  
    if increasing==False:
        y=np.column_stack([x**(N-i-1) for i in range (N)])
    else:
        y=np.column_stack([x**(i) for i in range (N)])
    return y
x=np.array([1,2,3,4])
N=len(x)
vander_mat(x,N,False)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [2]:
vander_mat(x,N,True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

##### Alternative Method

In [3]:
x = np.array([1, 2, 3, 4])
# input vector
N = 3
np.vander(x, N, increasing=False)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [4]:
np.vander(x, N, increasing=True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16]])

#### Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [5]:
x=[10,20,30,40,50,60,70,80,90,100]
k=4
n=len(x)
list=[]
for i in range(k,n+1):
    c=(x[i-k:i])
    z=np.sum(c)/k
    list.append(z)
print(list)

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]


Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [6]:
def mov_ave(x,k):
        val=[np.mean(x[i-k:i]) for i in range(k,len(x)+1)]
        return val
a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k=3
mov_ave(a,k)

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]